name: Auto Deploy Laravel

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: SSH Deploy
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          script: |
            cd /var/www/mahorapos
            git pull origin main
            composer install --no-dev --optimize-autoloader
            php artisan migrate:fresh --seed --force
            php artisan optimize:clear
            npm run build
            sudo chown -R nginx:nginx storage bootstrap/cache
            sudo chmod -R 775 storage bootstrap/cache
